name: 'Petitions polling'
on:
  push:
#  schedule:
#    - cron: "*/10 * * * *"

jobs:

  poll:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: make fetch
      - run: make update
