name: 'TAC/TAC-Vérif known banned QR-codes'
on:
  push:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  blacklists:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - run: ./match known_hashes > matches

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update blacklist
          commit_author: "[Bot] <actions@github.com>"
          file_pattern: banned_*

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update matches
          commit_author: "[Bot] <actions@github.com>"
          file_pattern: matches
