name: 'Petitions polling'
on:
  push:
  schedule:
    - cron: "*/10 * * * *"

jobs:

  brav-m:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - run: ./fetch-signatures-counts.sh

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update petitions counts
          commit_author: "[Bot] <actions@github.com>"
          commit_user_name: "[Bot]"
          commit_user_email: "actions@github.com"
          file_pattern: '*.txt'
