name: 'BRAV-M polling'
#on:
#  push:
#  schedule:
#    - cron: "*/10 * * * *"

jobs:

  brav-m:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - run: |
          : fetch brav-m petition signatures count
          (
          printf "$(date +'%F %T')\t"
          curl -s https://petitions.assemblee-nationale.fr/initiatives/i-1319 \
          | grep progress__bar__number \
          | sed 's/[^>]*>//; s/<.*//; s/ //'
          )  >> brav-m.txt

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update brav-m.txt
          commit_author: "[Bot] <actions@github.com>"
          file_pattern: brav-m.txt
