name: 'Petitions polling'
on:
  push:
  schedule:
    - cron: "*/10 * * * *"

jobs:

  brav-m:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - run: |
          : fetch petitions signatures counts

          fetch() {
          printf "$(TZ='Europe/Paris' date +'%F %T')\t"
          curl -s https://petitions.assemblee-nationale.fr/initiatives/$1 \
          | grep progress__bar__number \
          | sed 's/[^>]*>//; s/<.*//; s/ //'
          }

          fetch i-1446 >> brav-m.txt
          fetch i-1123 >> art-68.txt
          fetch i-1484 >> demission.txt
          fetch i-1549 >> lacrymo.txt
          fetch i-1395 >> art-68-v2.txt

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update petitions counts
          commit_author: "[Bot] <actions@github.com>"
          commit_user_name: "[Bot]"
          commit_user_email: "actions@github.com"
          file_pattern: '*.txt'
